services:
  - type: web
    name: glorious-student-tracker-em
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        sync: false
